/**
 * Created by willstreeter on 9/4/17.
 */

 const GC_MUTATION_TYPES = {
	GC_UPDATE_CURRENT_COLLECTION:'GC_UPDATE_CURRENT_COLLECTION',
  GC_RESET: 'GC_RESET',
  GC_APPEND: 'GC_APPEND',
  GC_TOTAL: 'GC_TOTAL'

}

export default GC_MUTATION_TYPES;
